version: '{build}'
skip_tags: true
image: Visual Studio 2017
configuration: Release
install:
build_script:
- ps: ./Build.ps1
test: off
artifacts:
- path: artifacts/Seq.Api.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: 7AS4wbHVs08D6so0JGAVczexCX9ST6CRbNToHZC08rtPqkQENpyNhhSAIX0FShzh
  skip_symbols: true
  on:
    branch: /^(master|dev)$/
- provider: GitHub
  auth_token:
    secure: hX+cZmW+9BCXy7vyH8myWsYdtQHyzzil9K5yvjJv7dK9XmyrGYYDj/DPzMqsXSjo
  artifact: /Seq.Api.*\.nupkg/
  tag: v$(appveyor_build_version)
  on:
    branch: master
